name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'public/.well-known/assetlinks.json'
      - 'firebase.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          # 常に最新のLTSを使いたい場合は 'lts/*' を指定

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Setup Firebase Service Account
        run: |
          echo '${{ secrets.FIREBASE_HOSTING_DEPLOY_SERVICE_ACCOUNT_JSON }}' > $HOME/only-firebasehosting-admin.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/only-firebasehosting-admin.json" >> $GITHUB_ENV

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --non-interactive